### ISSUE TITLE
Voting system

### ISSUE THREAD

**Issue by benw202** [flybywiresim/discord-bot-utils#20]
### Feature type

Utility or complex functionality

### Description

A voting system. Features to be discussed. 

### Discord Username (optional)

benw8484

**Comment by benw202** [comment]
cc: @FoxtrotSierra6829, @ImenesFBW - have mentioned you both as was brought up by you. Feel free to bring others in!

**Comment by FoxtrotSierra6829** [comment]
IMO it should take the following options:
- title
- context
- option 1 text
- option 2 text
(potentially more options)
- allow abstention ? (default true)
- end of vote (time left or UTC)
- roles to ping

**Comment by DJ45X** [comment]
going to start prototyping something tonight. i'll create a draft PR for feedback, tracking and such

**Comment by pdellaert** [comment]
@DJ45X, @benw202 already has an implementation that he's working on. So check with him first before continuing.

**Comment by benw202** [comment]
Closed due to Discord releasing their own polls feature. The branch will remain in case we wish to implement a custom polling solution in the future if the built in does not meet our needs.
