### ISSUE TITLE
Feature Request - Issues command to list github issues

### ISSUE THREAD

**Issue by pdellaert** [flybywiresim/discord-bot-utils#28]
### Feature type

Utility or complex functionality

### Description

Similar to the PR command, but for github issues instead

### Discord Username (optional)

straks

**Comment by benw202** [comment]
Perhaps we change this command to `/github` and have `pr` and `issues` as sub commands to keep our count down?

Also for future gh related command expandability

**Comment by pdellaert** [comment]
Sounds like a good idea!
