### ISSUE TITLE
[BUG] TypeScript v5.5 breaks build

### ISSUE THREAD

**Issue by ExampleWasTaken** [flybywiresim/discord-bot-utils#78]
# Description
A bug fix in TS v5.5 breaks our build.

It happens because `discord.js` export their own declarations for `node:events`. This causes TS to use those declarations instead of the ones from `@types/node` in [src/lib/db.ts#L16](https://github.com/flybywiresim/discord-bot-utils/blob/caa3e233995b802e7d2764990517eadbef06b54c/src/lib/db.ts#L16). These types being incorrect fails the build.

At the moment we use TypeScript `v5.3.3` which doesn't have the bug fix and therefore doesn't break our build.

## Expected behavior
TypeScript should use the correct types at all times.

## Steps to reproduce
1. Install the latest TypeScript version using 
```sh
npm i -D typescript@latest
```
2. Run
```sh
npm run dev
```

> [!IMPORTANT]
> VSCode users, make sure you use the workspace typescript version as VSC uses its bundled TS version by default.

> [!NOTE]
> Once done with testing, make sure to reset your workspace by running
> ```sh
> git reset --hard & npm i
> ```
 

## References
- discordjs/discord.js#10358
- https://github.com/microsoft/TypeScript/issues/58961#issuecomment-2185934861

**Comment by alepouna** [comment]
Seems like d.js is patching it with this PR https://github.com/discordjs/discord.js/pull/10360, once this is merged we can update d.js and it should be fine (?)

bug that became a feature for some, is now being patched 🤣

**Comment by ExampleWasTaken** [comment]
> Seems like d.js is patching it with this PR [discordjs/discord.js#10360](https://github.com/discordjs/discord.js/pull/10360), once this is merged we can update d.js and it should be fine (?)
> 
> bug that became a feature for some, is now being patched 🤣

Good spot! I'll subscribe to the PR and update our dependency once it's merged. (I hope it's that simple lol)

Feel free to assign me this issue :)

**Comment by ExampleWasTaken** [comment]
discordjs/discord.js#10360 has been merged, currently waiting on a new release from them

**Comment by ExampleWasTaken** [comment]
discord.js v14.16.0 has been [released](https://github.com/discordjs/discord.js/releases/tag/14.16.0) which includes the fix that's supposed to fix our issue.

I probably won't be able to work on it till the weekend though.
